### PR TITLE
Master

### PR DESCRIPTION
**Pull request by DJFliX**
I’ve updated the referenced nexe version to a more recent one, and implemented some extra options that are sent to nexe.

### CODE REVIEW

**Comment by e-jigsaw** [comment]
This repository no longer maintained. If you want maintain this repo/npm then I will add collaborators.

Thanks

**Comment by DJFliX** [comment]
That would be splendid, thank you!

**Comment by e-jigsaw** [comment]
@DJFliX OK, I added you as a collaborator! Next, do you have npm account?

**Comment by DJFliX** [comment]
Thanks! Yes, I’ve created one today. I use the same handle as on github.

Regards,

**Comment by e-jigsaw** [comment]
@DJFliX OK, I added npm collaborator too. Now you can publish new version of `grunt-nexe`!

**Comment by DJFliX** [comment]
Thank you very much! And of course, thank you for your work on the repository! 

Regards,

Felix

**Comment by e-jigsaw** [comment]
OK, then now this PR can merge?

**Pull request merged**
